//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string idTaiKhoan { get; set; }
        public string email { get; set; }
        public string soDienThoai { get; set; }
        public string ho { get; set; }
        public string ten { get; set; }
        public string matKhau { get; set; }
        public string matKhauQT { get; set; }
        public int maNhom { get; set; }
        public int sttTrangThai { get; set; }
        public string diaChi { get; set; }
    }
}
