//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuongHieu
    {
        public int maThuongHieu { get; set; }
        public string tenThuongHieu { get; set; }
        public string moTa { get; set; }
        public virtual ICollection<SanPham> SanPhams{ get; set; }

    }
}
